# Generated by Django 4.0.1 on 2022-01-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default='', upload_to='product pics'),
            preserve_default=False,
        ),
    ]
